modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "random_mh"
version = "${version}"
displayName = "Random ManHunt"
authors = ""
description = '''
Random manhunt! No more words needed.
'''
logoFile = "assets/random_mh/icon.png"

[[dependencies.random_mh]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.random_mh]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.random_mh]]
modId = "architectury"
type = "required"
versionRange = "[19.0.1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "random_mh.mixins.json"
